<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Automaton.0.4.0</PackageId>
    <Version>0.4.0</Version>
    <Author>OpyrusDevOp</Author>
  </PropertyGroup>

</Project>
